# Generated by Django 4.1.4 on 2023-01-13 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpeakHere_app', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
    ]
