# Generated by Django 4.1.4 on 2023-01-28 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpeakHere_app', '0011_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='notifications_type',
            new_name='notification_type',
        ),
    ]
