# Generated by Django 4.1.4 on 2023-01-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeakHere_app', '0012_rename_notifications_type_notifications_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='uploads/post_photo'),
            preserve_default=False,
        ),
    ]
