# Generated by Django 4.1.4 on 2023-01-30 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpeakHere_app', '0016_notifications_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threadnot', to='SpeakHere_app.threadmodel'),
        ),
    ]
